server:
  port: 8081
  
spring:
  application:
    name: dept-service
  profiles:
    active: dev

  thymeleaf:
    cache: false

  redis:
    port: 6379
    host: localhost
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  rabbitmq:
    port: 5672

#mybatis-plus:
#  mapper-locations: classpath*:/mybatis1/**/*.xml
  
logging:
  level:
    '[com.hj.dao]': info

eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）
  instance: