spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myshop?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root